# timescaledb
- name: timescaledb - download & install dependencies
  apt:
    pkg:
      - cmake
    update_cache: yes
    install_recommends: no

- name: timescaledb - download latest release
  git:
    repo: https://github.com/timescale/timescaledb.git
    dest: /tmp/timescaledb
    version: "{{ timescaledb_release }}"
  become: yes

- name: timescaledb - bootstrap
  shell:
    cmd: "./bootstrap -DAPACHE_ONLY=1 -DREGRESS_CHECKS=OFF"
    chdir: /tmp/timescaledb
  become: yes

- name: timescaledb - build
  make:
    chdir: /tmp/timescaledb/build
  become: yes

- name: timescaledb - install
  make:
    chdir: /tmp/timescaledb/build
    target: install
  become: yes

- name: timescaledb - add timescaledb to shared_preload_libraries
  become: yes
  replace:
    path: /etc/postgresql/postgresql.conf
    regexp: 'shared_preload_libraries = ''(.*)''(.*)'
    replace: 'shared_preload_libraries = ''\1, timescaledb''\2'
